Keep queue dirs from sprawling, delete empty.

diff --git a/msmtp-runqueue b/msmtp-runqueue
--- a/msmtp-runqueue
+++ b/msmtp-runqueue
@@ -25,35 +25,34 @@ fi
 cd "$QUEUEDIR" || exit 1
 
 # check for empty queuedir
-if [ "`echo *.mail`" = '*.mail' ]; then
-    exit 0
+if [ ! "`echo *.mail`" = '*.mail' ]; then
+
+    # lock the $QUEUEDIR
+    touch "$LOCKFILE" || exit 1
+
+    # process all mails
+    for MAILFILE in *.mail; do
+        MSMTPFILE="`echo $MAILFILE | sed -e 's/mail/msmtp/'`"
+        echo "*** Sending $MAILFILE to `sed -e 's/^.*-- \(.*$\)/\1/' $MSMTPFILE` ..."
+        if [ ! -f "$MSMTPFILE" ]; then
+            echo "No corresponding file $MSMTPFILE found"
+            echo "FAILURE"
+            continue
+        fi
+        msmtp $OPTIONS `cat "$MSMTPFILE"` < "$MAILFILE"
+        if [ $? -eq 0 ]; then
+            rm "$MAILFILE" "$MSMTPFILE"
+            echo "$MAILFILE sent successfully"
+        else
+            echo "FAILURE"
+        fi
+    done
+
+    # remove the lock
+    rm -f "$LOCKFILE"
 fi
 
-# lock the $QUEUEDIR
-touch "$LOCKFILE" || exit 1
-
-# process all mails
-for MAILFILE in *.mail; do
-    MSMTPFILE="`echo $MAILFILE | sed -e 's/mail/msmtp/'`"
-    echo "*** Sending $MAILFILE to `sed -e 's/^.*-- \(.*$\)/\1/' $MSMTPFILE` ..."
-    if [ ! -f "$MSMTPFILE" ]; then
-        echo "No corresponding file $MSMTPFILE found"
-        echo "FAILURE"
-        continue
-    fi
-    msmtp $OPTIONS `cat "$MSMTPFILE"` < "$MAILFILE"
-    if [ $? -eq 0 ]; then
-        rm "$MAILFILE" "$MSMTPFILE"
-        echo "$MAILFILE sent successfully"
-    else
-        echo "FAILURE"
-    fi
-done
-
-# remove the lock
-rm -f "$LOCKFILE"
-
 # remove empty queue dir
-cd & rmdir --ignore-fail-on-non-empty $QUEUEDIR
+cd && rmdir --ignore-fail-on-non-empty $QUEUEDIR
 
 exit 0
